name: Ejecutar IBEX diario

permissions:
  contents: write

on:
  schedule:
    - cron: '30 16 * * 1-5'
  workflow_dispatch:

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install yfinance pandas requests lxml html5lib

    - name: Ejecutar script
      run: python top5ibex.py

    - name: Guardar CSV
      uses: actions/upload-artifact@v4
      with:
        name: ibex-resultados
        path: ibex35_top5_caidas_subidas.csv

    - name: Guardar resultados en repo
      run: |
        mkdir -p resultados
        cp ibex35_top5_caidas_subidas.csv resultados/

    - name: Commit resultados
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add resultados/
        git commit -m "Actualización automática IBEX" || exit 0
        git push


  
