name: Test escritura

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Crear carpeta y archivo
        run: |
          mkdir -p resultados
          echo "Prueba $(date)" > resultados/test.txt

      - name: Ver contenido
        run: |
          ls -R

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Prueba carpeta resultados"
          file_pattern: resultados/test.txt
